In [1]:
import torch
import numpy as np

In [3]:
x = torch.rand(2,3)
y = torch.ones(x.size())
print(x,y)

tensor([[0.6879, 0.1987, 0.5297],
        [0.1692, 0.3491, 0.4382]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:

# Other common initialization methods (there exists a ton more)
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.zeros((3, 3))  # Tensor of shape 3x3 with values of 0
x = torch.rand((3, 3))  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
x

tensor([[0.3167, 0.3000, 0.6178],
        [0.6631, 0.4331, 0.3072],
        [0.1302, 0.7735, 0.3374]])

In [6]:
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
x = torch.arange(
    start=0, end=5, step=1
)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(11)
print(f"x arange - {x}")
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
print(f"x linespace {x}")

x arange - tensor([0, 1, 2, 3, 4])
x linespace tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [10]:
# How to make initialized tensors to other types (int, float, double)
# These will work even if you're on CPU or CUDA!
tensor = torch.arange(4)  # [0, 1, 2, 3] Initialized as int64 by default
print(f"Converted Boolean: {tensor.bool()}")  # Converted to Boolean: 1 if nonzero
print(f"Converted int16 {tensor.short()}")  # Converted to int16
print(
    f"Converted int64 {tensor.long()}"
)  # Converted to int64 (This one is very important, used super often)
print(f"Converted float16 {tensor.half()}")  # Converted to float16
print(
    f"Converted float32 {tensor.float()}"
)  # Converted to float32 (This one is very important, used super often)
print(f"Converted float64 {tensor.double()}")  # Converted to float64

# Array to Tensor conversion and vice-versa
import numpy as np

np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_again = (tensor.numpy())  # np_array_again will be same as np_array (perhaps with numerical round offs)
np_array_again

Converted Boolean: tensor([False,  True,  True,  True])
Converted int16 tensor([0, 1, 2, 3], dtype=torch.int16)
Converted int64 tensor([0, 1, 2, 3])
Converted float16 tensor([0., 1., 2., 3.], dtype=torch.float16)
Converted float32 tensor([0., 1., 2., 3.])
Converted float64 tensor([0., 1., 2., 3.], dtype=torch.float64)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
x.add_(1) # _ indicated inplace

tensor([1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000, 1.9000,
        2.0000])

In [13]:
b = np.random.rand(2,3)
bt = torch.from_numpy(b)

#b and bt share memory, any change to bt will lead to change in b too. ****
print("b before = ",b)
bt.add_(1)
print("b after = ",b)

b before =  [[0.83058354 0.58681359 0.64861697]
 [0.00385951 0.44864468 0.7399875 ]]
b after =  [[1.83058354 1.58681359 1.64861697]
 [1.00385951 1.44864468 1.7399875 ]]


In [14]:
# -- Matrix Multiplication --
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
x3

tensor([[0.1339, 0.5535, 0.6276],
        [0.9000, 1.6533, 1.6484]])

In [16]:
x3 = x1.mm(x2)  # Similar as above
x3

tensor([[0.1339, 0.5535, 0.6276],
        [0.9000, 1.6533, 1.6484]])

In [21]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# -- Element wise Multiplication --
z = x * y  # z = [9, 16, 21] = [1*9, 2*8, 3*7]
z

tensor([ 9, 16, 21])

In [22]:
# -- Dot product --
z = torch.dot(x, y)  # Dot product, in this case z = 1*9 + 2*8 + 3*7
z

tensor(46)

## Basic ANN

In [5]:
import torch
import torchvision.datasets as datasets  # Has standard datasets we can import in a nice way
import torchvision.transforms as transforms  # Transformations we can perform on our dataset
import torch.nn as nn
import torchvision as tv
from torch.utils.data import DataLoader, Dataset

In [2]:
# Set device
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = "cpu"
# Hyperparameters
input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64
num_epochs = 5

In [3]:
# we will use Mnist dataset which is already available in pytorch
# define transformations on Images
transform = transforms.Compose([transforms.ToTensor()])

train_ds = datasets.MNIST( root="data/",train=True,download = True,transform= transform)
test_ds = datasets.MNIST( root="data/",train=False,download = True,transform= transform)
train_ds.data.shape

torch.Size([60000, 28, 28])

In [4]:
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=True)
next(iter(train_loader))

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         ...,
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ..

In [5]:
# (input image, targets)

In [6]:
import torch.nn.functional as F

class ANN(nn.Module):
    def __init__(self,input_size, num_classes):
        super().__init__()
        self.fc1 = nn.Linear(input_size,128)
        self.fc2 = nn.Linear(128,64)
        self.fc3 = nn.Linear(64,32)
        self.fc4 = nn.Linear(32, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
#         print(x.shape)
        x = F.relu(self.fc2(x))
#         print(x.shape)
        x = F.relu(self.fc3(x))
#         print(x.shape)
        x = self.fc4(x)
        out = F.softmax(x,dim=1) # dim = 1 because s is (64,10) and we want to take softmax over 10 which are vectors.
        
        return out

  
model = ANN(input_size=input_size, num_classes=num_classes).to(device)
model

ANN(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=32, bias=True)
  (fc4): Linear(in_features=32, out_features=10, bias=True)
)

In [7]:
# weights are randomply initialized in torch
print(model.fc2.weight)
print(model.fc2.bias)

Parameter containing:
tensor([[-0.0330,  0.0226, -0.0430,  ...,  0.0633,  0.0185, -0.0303],
        [ 0.0124,  0.0480, -0.0161,  ...,  0.0804, -0.0016,  0.0276],
        [ 0.0490, -0.0535, -0.0354,  ...,  0.0407,  0.0349,  0.0358],
        ...,
        [-0.0480, -0.0480, -0.0105,  ...,  0.0438,  0.0338,  0.0123],
        [-0.0076, -0.0445,  0.0682,  ..., -0.0468,  0.0225,  0.0880],
        [ 0.0368,  0.0655,  0.0045,  ...,  0.0242, -0.0707,  0.0334]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0866,  0.0303,  0.0410, -0.0585,  0.0266, -0.0801, -0.0275, -0.0742,
        -0.0065,  0.0402, -0.0150, -0.0283,  0.0569, -0.0259,  0.0640, -0.0877,
         0.0739, -0.0327,  0.0378, -0.0632, -0.0836, -0.0822, -0.0607, -0.0723,
         0.0393, -0.0377,  0.0524,  0.0635,  0.0086,  0.0318, -0.0319,  0.0583,
        -0.0227, -0.0612, -0.0624,  0.0344, -0.0289,  0.0876,  0.0483, -0.0677,
        -0.0622,  0.0290, -0.0061, -0.0816, -0.0759, -0.0394,  0.0845, -0.0495,
         0.0547

In [8]:
oneBatch = next(iter(train_loader))[0]
print("batch = ",oneBatch.shape)
model(oneBatch.reshape(64, -1))

batch =  torch.Size([64, 1, 28, 28])


tensor([[0.1081, 0.0949, 0.1011, 0.0954, 0.1038, 0.0957, 0.1150, 0.1074, 0.0882,
         0.0904],
        [0.1072, 0.0967, 0.0997, 0.0961, 0.1042, 0.0954, 0.1148, 0.1075, 0.0882,
         0.0903],
        [0.1089, 0.0969, 0.1005, 0.0952, 0.1034, 0.0966, 0.1123, 0.1085, 0.0885,
         0.0892],
        [0.1084, 0.0954, 0.1009, 0.0956, 0.1048, 0.0955, 0.1138, 0.1070, 0.0879,
         0.0907],
        [0.1088, 0.0952, 0.1003, 0.0960, 0.1031, 0.0962, 0.1131, 0.1080, 0.0890,
         0.0903],
        [0.1079, 0.0975, 0.0981, 0.0974, 0.1043, 0.0948, 0.1143, 0.1060, 0.0885,
         0.0910],
        [0.1082, 0.0975, 0.0981, 0.0972, 0.1029, 0.0950, 0.1130, 0.1080, 0.0897,
         0.0905],
        [0.1086, 0.0947, 0.1020, 0.0950, 0.1036, 0.0956, 0.1145, 0.1075, 0.0884,
         0.0901],
        [0.1073, 0.0965, 0.0997, 0.0970, 0.1047, 0.0953, 0.1130, 0.1059, 0.0889,
         0.0916],
        [0.1084, 0.0953, 0.1011, 0.0962, 0.1044, 0.0956, 0.1143, 0.1063, 0.0878,
         0.0907],
        [0

In [9]:
# Sequential way 
in_s = 784
h = [128,64,32]
out = 10

model_s = nn.Sequential(nn.Linear(in_s,h[0]),
                        nn.ReLU(),
                        nn.Linear(h[0],h[1]),
                        nn.ReLU(),
                        nn.Linear(h[1],h[2]),
                        nn.ReLU(),
                        nn.Linear(h[2],out),
                        nn.Softmax(dim=1),
                        )

print(model_s)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=10, bias=True)
  (7): Softmax(dim=1)
)


In [15]:
for idx, (inputImg, target) in enumerate(train_loader):
    if inputImg.shape != (64,1,28,28):
        print(inputImg.shape)

torch.Size([32, 1, 28, 28])


In [10]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [16]:
def train(epochs):
    for epoch in range(epochs):
        for idx, (inputImg, target) in enumerate(train_loader):
            
            inputImg = inputImg.to(device)
            target = target.to(device)
            
            # reshape as the data will be in form (64,1,28,28) and we want (64,784)
            inputImg = inputImg.reshape(inputImg.shape[0],-1)
            # forward
            scores = model(inputImg)
            
            #get loss
            loss = criterion(scores, target)

            # backward
            optimizer.zero_grad()
            loss.backward()

            # gradient descent or adam step
            optimizer.step()

train(2)

In [17]:
def check_accuracy(loader, model):
    if loader.dataset.train:
        print("Checking accuracy on training data")
    else:
        print("Checking accuracy on test data")

    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device)
            y = y.to(device=device)
            x = x.reshape(x.shape[0], -1)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions == y).sum()
            num_samples += predictions.size(0)

        print(
            f"Got {num_correct} / {num_samples} with accuracy {float(num_correct)/float(num_samples)*100:.2f}"
        )

    model.train()
    
check_accuracy(test_loader, model)

Checking accuracy on test data
Got 9559 / 10000 with accuracy 95.59


## Let's build a CNN

In [29]:
class CustomCNN(nn.Module):
    def __init__(self, in_channels=1, num_classes=10):
        super(CustomCNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=8, kernel_size=(3, 3), stride=(1, 1),padding=(1, 1))
        self.pool = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv2 = nn.Conv2d(8, 16, kernel_size=3)
        self.fc1 = nn.Linear(16 * 6 * 6, num_classes)
        
    def forward(self,x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
#         print(x.shape)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
#         print(x.shape)
        x = x.reshape(x.shape[0], -1)
#         print(x.shape)
        out = self.fc1(x)
#         print(x.shape)
        return out
    
model = CustomCNN().to(device)
model

CustomCNN(
  (conv1): Conv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=10, bias=True)
)

In [30]:
oneBatch.shape

torch.Size([64, 1, 28, 28])

In [31]:
model(oneBatch)

tensor([[-1.2303e-02, -4.0456e-02,  2.6771e-02, -4.8776e-02, -5.6176e-02,
          8.0413e-02, -3.2589e-02,  4.2463e-02,  4.6010e-02,  5.2764e-03],
        [-8.3632e-02, -4.5662e-02,  3.2310e-02,  1.9257e-02, -4.1453e-02,
          1.0438e-01, -3.9681e-02,  3.9976e-02,  1.4651e-02,  9.0973e-03],
        [-6.2059e-02,  7.7991e-03,  5.5779e-02, -3.8301e-02, -1.5751e-02,
          9.5194e-02, -7.8704e-02,  2.0113e-02,  5.9643e-02, -1.7934e-02],
        [-3.4122e-02, -2.2698e-02,  8.7814e-02,  1.2625e-03, -9.2570e-02,
          7.9959e-02, -1.2639e-01,  2.7606e-02,  2.9502e-02, -4.2889e-02],
        [-1.1404e-02, -4.1271e-02,  4.6669e-02, -8.2203e-03, -4.3626e-02,
          9.0196e-02, -1.0468e-01,  2.6837e-03,  3.9210e-02, -2.0851e-03],
        [-4.2037e-02,  4.5405e-03,  3.2171e-02, -2.1225e-02,  3.4474e-03,
          1.0789e-01, -5.8936e-02,  6.0544e-02,  1.9023e-02,  7.6452e-03],
        [-3.4143e-02, -2.4833e-02,  8.9617e-02,  4.6181e-03, -3.8564e-03,
          8.1897e-02, -1.0757e-0

## Let's build a RNN

In [32]:
# Hyperpaarameters will be slightly different
# same hidden state is shared between RNN so we will make 1

input_size = 28
sequence_length = 28
hidden_size = 256
num_layers = 2
num_classes = 10
learning_rate = 0.005
batch_size = 64
num_epochs = 2

In [35]:
class CustomRNN(nn.Module):
    def __init__(self,input_size,num_layers,hidden_size,num_classes):
        super(CustomRNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size * sequence_length, num_classes) # h*seq_length because every hidden layer will be returned by default
        
    def forward(self,x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) # n_layer x batch x hidden_size
        
        # Forward propagate LSTM
        out, _ = self.rnn(x, h0) # pass both input and hidden_layer
        
        # reshape for Linear Layer
        out = out.reshape(out.shape[0], -1)
                
        # Decode the hidden state of the last time step
        out = self.fc(out)
        return out
    
    
model = CustomRNN(input_size,num_layers,hidden_size,num_classes).to(device)
model

CustomRNN(
  (rnn): RNN(28, 256, num_layers=2, batch_first=True)
  (fc): Linear(in_features=7168, out_features=10, bias=True)
)

In [37]:
print(oneBatch.shape)
print(f"After Squeezing {oneBatch.squeeze(1).shape}")
model(oneBatch.squeeze(1)) 

torch.Size([64, 1, 28, 28])
After Squeezing torch.Size([64, 28, 28])


tensor([[-7.7867e-03,  5.4862e-02,  1.7002e-02,  6.4441e-02,  5.2487e-02,
          2.8914e-02,  1.5277e-01, -1.9888e-02,  1.2032e-02,  7.9564e-03],
        [-6.4290e-02,  2.7693e-02,  1.8062e-02,  4.5737e-02,  6.1575e-02,
          8.9556e-02,  1.3377e-01, -1.7753e-02, -1.5532e-02,  2.5969e-02],
        [-1.8605e-02,  5.4065e-02,  5.8990e-02,  7.6414e-02,  9.7907e-02,
          3.6185e-02,  1.3990e-01, -4.0081e-02, -4.1888e-02,  1.6626e-02],
        [-2.2491e-02,  1.5034e-02,  3.7233e-02,  4.1070e-02,  4.6367e-02,
          1.2386e-02,  1.4849e-01, -3.1737e-02,  1.0489e-02, -1.4226e-02],
        [-7.5412e-03,  4.6539e-02,  2.2524e-02,  5.7146e-02,  7.8986e-02,
          3.1752e-03,  1.2871e-01, -7.5431e-02, -7.0431e-02, -1.6278e-03],
        [-6.0760e-03,  5.3313e-02,  3.0501e-02,  2.3270e-02,  4.9809e-02,
          4.0186e-02,  1.2841e-01, -7.7128e-02, -8.2093e-02, -3.7051e-02],
        [-6.3949e-02,  5.7773e-02,  5.3589e-02,  5.7718e-02,  8.8511e-03,
          2.4711e-02,  1.4395e-0

## Let's build a LSTM

In [40]:
class CustomLSTM(nn.Module):
    def __init__(self,input_size,num_layers,hidden_size,num_classes):
        super(CustomLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.rnn = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size * sequence_length, num_classes) # h*seq_length because every hidden layer will be returned by default
        
    def forward(self,x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) # n_layer x batch x hidden_size
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) # LSTM requires a new state, cell state
        # Forward propagate LSTM
        out, _ = self.rnn(x, (h0,c0)) # pass both input and hidden_layer
        
        # reshape for Linear Layer
        out = out.reshape(out.shape[0], -1)
                
        # Decode the hidden state of the last time step
        out = self.fc(out)
        return out
    
    
model = CustomLSTM(input_size,num_layers,hidden_size,num_classes).to(device)
model

CustomLSTM(
  (rnn): LSTM(28, 256, num_layers=2, batch_first=True)
  (fc): Linear(in_features=7168, out_features=10, bias=True)
)

In [41]:
print(oneBatch.shape)
print(f"After Squeezing {oneBatch.squeeze(1).shape}")
model(oneBatch.squeeze(1)) 

torch.Size([64, 1, 28, 28])
After Squeezing torch.Size([64, 28, 28])


tensor([[-1.6261e-02, -1.2251e-02,  4.8639e-03,  6.7531e-03,  1.4366e-02,
          6.5362e-03,  6.9961e-03,  2.8711e-02, -1.8575e-02, -1.5726e-02],
        [-1.0902e-02, -1.5688e-02,  1.3378e-02, -6.5024e-03,  1.3055e-02,
          1.0772e-02,  1.2000e-02,  2.4829e-02, -2.0023e-02, -1.5289e-02],
        [-2.5723e-03, -9.1180e-03,  5.5391e-05, -1.6861e-05,  1.9458e-02,
         -7.3156e-04,  9.9882e-03,  2.6085e-02, -1.8771e-02, -1.0173e-02],
        [-1.5172e-02, -6.6282e-03,  2.3658e-03,  1.4876e-03,  1.6678e-02,
          4.3901e-03,  6.4023e-03,  2.8412e-02, -2.4311e-02, -2.1052e-02],
        [-9.9479e-03, -4.6030e-03,  2.3462e-03, -5.2898e-03,  1.8700e-02,
          2.0758e-03,  6.7418e-03,  2.8708e-02, -1.8640e-02, -1.5588e-02],
        [-1.7689e-02, -1.4401e-02,  1.3802e-02, -1.1303e-02,  1.4465e-02,
          9.4364e-03, -6.1938e-05,  2.7945e-02, -1.6641e-02, -1.7132e-02],
        [-1.0052e-02, -1.1185e-02,  2.5419e-03, -3.0387e-03,  1.6449e-02,
          8.4674e-03,  6.4157e-0

## Making a Custom DataSet 

In [10]:
# let's make a custom dataset for a folder with Images and a csv file denoting target value for each image
from PIL import Image
import pandas as pd

class CustomDataSet(Dataset):
    def __init__(self, csv_file, root_dir, transform = None):
        self.annotations = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform
    
    def __len__(self):
        return len(self.annotations)
    
    def __getitem__(self, index):
        # define path to image
        img_path = os.path.join(self.root_dir, self.annotations.iloc[index, 0])
        image = Image.open(img_path)
        
        if self.transform:
            image = self.transform(image)
        
        y_label = torch.tensor(int(self.annotations.iloc[index, 1]))
        
        return (image, y_label)

# Load Data
dataset = CustomDataSet(csv_file = "X.csv", root_dir="./", transform = transforms.ToTensor())
dataset

/home/alaap/projects/env_py3.6/lib/python3.6/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


FileNotFoundError: [Errno 2] No such file or directory: 'X.csv'