In [2]:
import torch
import numpy as np

In [3]:
x = torch.rand(2,3)
y = torch.ones(x.size())
print(x,y)

tensor([[0.6879, 0.1987, 0.5297],
        [0.1692, 0.3491, 0.4382]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:

# Other common initialization methods (there exists a ton more)
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.zeros((3, 3))  # Tensor of shape 3x3 with values of 0
x = torch.rand((3, 3))  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
x

tensor([[0.3167, 0.3000, 0.6178],
        [0.6631, 0.4331, 0.3072],
        [0.1302, 0.7735, 0.3374]])

In [6]:
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
x = torch.arange(
    start=0, end=5, step=1
)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(11)
print(f"x arange - {x}")
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
print(f"x linespace {x}")

x arange - tensor([0, 1, 2, 3, 4])
x linespace tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [10]:
# How to make initialized tensors to other types (int, float, double)
# These will work even if you're on CPU or CUDA!
tensor = torch.arange(4)  # [0, 1, 2, 3] Initialized as int64 by default
print(f"Converted Boolean: {tensor.bool()}")  # Converted to Boolean: 1 if nonzero
print(f"Converted int16 {tensor.short()}")  # Converted to int16
print(
    f"Converted int64 {tensor.long()}"
)  # Converted to int64 (This one is very important, used super often)
print(f"Converted float16 {tensor.half()}")  # Converted to float16
print(
    f"Converted float32 {tensor.float()}"
)  # Converted to float32 (This one is very important, used super often)
print(f"Converted float64 {tensor.double()}")  # Converted to float64

# Array to Tensor conversion and vice-versa
import numpy as np

np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_again = (tensor.numpy())  # np_array_again will be same as np_array (perhaps with numerical round offs)
np_array_again

Converted Boolean: tensor([False,  True,  True,  True])
Converted int16 tensor([0, 1, 2, 3], dtype=torch.int16)
Converted int64 tensor([0, 1, 2, 3])
Converted float16 tensor([0., 1., 2., 3.], dtype=torch.float16)
Converted float32 tensor([0., 1., 2., 3.])
Converted float64 tensor([0., 1., 2., 3.], dtype=torch.float64)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
x.add_(1) # _ indicated inplace

tensor([1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000, 1.9000,
        2.0000])

In [13]:
b = np.random.rand(2,3)
bt = torch.from_numpy(b)

#b and bt share memory, any change to bt will lead to change in b too. ****
print("b before = ",b)
bt.add_(1)
print("b after = ",b)

b before =  [[0.83058354 0.58681359 0.64861697]
 [0.00385951 0.44864468 0.7399875 ]]
b after =  [[1.83058354 1.58681359 1.64861697]
 [1.00385951 1.44864468 1.7399875 ]]


In [14]:
# -- Matrix Multiplication --
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
x3

tensor([[0.1339, 0.5535, 0.6276],
        [0.9000, 1.6533, 1.6484]])

In [16]:
x3 = x1.mm(x2)  # Similar as above
x3

tensor([[0.1339, 0.5535, 0.6276],
        [0.9000, 1.6533, 1.6484]])

In [21]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# -- Element wise Multiplication --
z = x * y  # z = [9, 16, 21] = [1*9, 2*8, 3*7]
z

tensor([ 9, 16, 21])

In [22]:
# -- Dot product --
z = torch.dot(x, y)  # Dot product, in this case z = 1*9 + 2*8 + 3*7
z

tensor(46)

In [ ]:
from torchvision import datasets,transforms

transform = transforms.Compose([transforms.ToTensor(),
                               transforms.Normalize((.5,.5,.5),(.5,.5,.5))])

trainset = datasets.MNIST('MNIST_data/',download = True, train=True, transform= transform)

Extracting MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to MNIST_data/MNIST/raw


Extracting MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw


Extracting MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST_data/MNIST/raw




Extracting MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw
Processing...
Done!


In [ ]:
print(trainset.data.shape)
trainloader = torch.utils.data.DataLoader(trainset,batch_size=64,shuffle=True)


testset = datasets.MNIST('MNIST_data/',download = True, train=False, transform= transform)
testloader = torch.utils.data.DataLoader(testset,batch_size=64,shuffle=True)


torch.Size([60000, 28, 28])


In [ ]:
from torch import nn
import torch.nn.functional as F

class Network(nn.Module):
    def __init__(self):
     super().__init__()

     self.fc1 = nn.Linear(784,128)
     self.fc2 = nn.Linear(128,64)
     self.fc3 = nn.Linear(64,32)
     self.fc4 = nn.Linear(32,10)

    def forward(self, x):
      x = self.fc1(x)
      x = F.relu(x)
      x = self.fc2(x)
      x = F.relu(x)
      x = self.fc3(x)
      x = F.relu(x)
      x = self.fc4(x)
      x = F.softmax(x,dim=1) # dim = 1 because s is (64,10) and we want to take softmax over 10 which are vectors.

      return x

  
model = Network()
model

Network(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=32, bias=True)
  (fc4): Linear(in_features=32, out_features=10, bias=True)
)

In [ ]:
print(model.fc2.weight)
print(model.fc2.bias)

Parameter containing:
tensor([[ 0.0764, -0.0077,  0.0483,  ..., -0.0005, -0.0326,  0.0854],
        [ 0.0202,  0.0630,  0.0780,  ..., -0.0111, -0.0251,  0.0270],
        [ 0.0473,  0.0327, -0.0033,  ..., -0.0460,  0.0873,  0.0341],
        ...,
        [ 0.0423,  0.0486, -0.0448,  ...,  0.0357,  0.0681,  0.0090],
        [ 0.0807, -0.0642,  0.0867,  ...,  0.0799, -0.0736, -0.0228],
        [ 0.0731,  0.0672, -0.0756,  ..., -0.0581, -0.0626,  0.0238]],
       requires_grad=True)
Parameter containing:
tensor([-0.0397,  0.0752,  0.0804,  0.0005, -0.0298, -0.0051, -0.0316, -0.0845,
        -0.0837, -0.0150,  0.0820, -0.0608,  0.0425,  0.0807,  0.0132,  0.0329,
         0.0378,  0.0473,  0.0549, -0.0407, -0.0182,  0.0348,  0.0644,  0.0243,
        -0.0580, -0.0449,  0.0331,  0.0780,  0.0143, -0.0264,  0.0240,  0.0592,
         0.0854, -0.0570,  0.0417,  0.0876, -0.0845, -0.0767, -0.0306,  0.0119,
        -0.0444,  0.0664, -0.0643, -0.0033,  0.0444,  0.0876, -0.0301, -0.0158,
        -0.0833

In [ ]:
# SEquential way 

in_s = 784
h = [128,64,32]
out = 10

model_s = nn.Sequential(nn.Linear(in_s,h[0]),
                        nn.ReLU(),
                        nn.Linear(h[0],h[1]),
                        nn.ReLU(),
                        nn.Linear(h[1],h[2]),
                        nn.ReLU(),
                        nn.Linear(h[2],out),
                        nn.Softmax(dim=1),
                        )

print(model_s)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=10, bias=True)
  (7): Softmax(dim=1)
)


In [ ]:
# loading data

d = datasets.ImageGolder('/path/',transform=transform)
dataloader = torch.utils.data.DataLoader(d,batch_size=64)

###**Example of simple Linear Regression**

In [ ]:
 class LinearRegression(nn.Module):
    def __init__(self,input,output):
     super(LinearRegression,self).__init__()
     self.linear = nn.Linear(input,output)

    def forward(self, x):
        out = self.linear(x)
        return out

In [ ]:
x_values = [i for i in range(10)]
X_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)

In [ ]:
input_dim,output_dim = 1,1

model = LinearRegression(input_dim,output=output_dim)

criterion = nn.MSELoss()

lr=0.01

optimizer = torch.optim.Adam(model.parameters(),lr=lr)

In [ ]:
print(X_train[:5],y_train[:5])

[0. 1. 2. 3. 4.] [[1.]
 [3.]
 [5.]
 [7.]
 [9.]]


In [ ]:
epochs = 200

for epoch in range(epochs):
  epoch += 1

  inputs = torch.from_numpy(np.asarray(X_train, dtype=np.float32).reshape(-1,1))
  labels = torch.from_numpy(np.asarray(y_train, dtype=np.float32).reshape(-1,1))

  optimizer.zero_grad()

  outputs = model(inputs)

  loss = criterion(outputs,labels)
  loss.backward()

  optimizer.step()

  if (epoch+1) % 5 == 0:
    print ('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, loss.item()))


Epoch [5/200], Loss: 53.6547
Epoch [10/200], Loss: 49.2254
Epoch [15/200], Loss: 45.0144
Epoch [20/200], Loss: 41.0328
Epoch [25/200], Loss: 37.2878
Epoch [30/200], Loss: 33.7826
Epoch [35/200], Loss: 30.5169
Epoch [40/200], Loss: 27.4873
Epoch [45/200], Loss: 24.6879
Epoch [50/200], Loss: 22.1107
Epoch [55/200], Loss: 19.7465
Epoch [60/200], Loss: 17.5851
Epoch [65/200], Loss: 15.6158
Epoch [70/200], Loss: 13.8274
Epoch [75/200], Loss: 12.2086
Epoch [80/200], Loss: 10.7483
Epoch [85/200], Loss: 9.4354
Epoch [90/200], Loss: 8.2590
Epoch [95/200], Loss: 7.2086
Epoch [100/200], Loss: 6.2739
Epoch [105/200], Loss: 5.4452
Epoch [110/200], Loss: 4.7131
Epoch [115/200], Loss: 4.0688
Epoch [120/200], Loss: 3.5038
Epoch [125/200], Loss: 3.0102
Epoch [130/200], Loss: 2.5806
Epoch [135/200], Loss: 2.2082
Epoch [140/200], Loss: 1.8866
Epoch [145/200], Loss: 1.6100
Epoch [150/200], Loss: 1.3729
Epoch [155/200], Loss: 1.1706
Epoch [160/200], Loss: 0.9985
Epoch [165/200], Loss: 0.8528
Epoch [170/200

In [ ]:
# Linear Regression without nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# INPUT SHOULD IDEALLY BE EQUAL TO OUTPUTS 

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)



In [ ]:
targets.shape

torch.Size([5, 2])

In [ ]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.0395, -0.8919,  0.2278],
        [-1.9419,  0.2047, -1.4766]], requires_grad=True)
tensor([-0.3921,  0.5929], requires_grad=True)


In [ ]:
def model(x):
    #take input and do a forward pass
    return x @ w.t() + b

preds = model(inputs)
preds

tensor([[ -53.2430, -190.9400],
        [ -67.9017, -252.6027],
        [-110.1394, -226.5582],
        [ -34.3499, -243.3081],
        [ -72.8007, -217.1033]], grad_fn=<AddBackward0>)

In [ ]:

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(63463.6562, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

In [ ]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.0395, -0.8919,  0.2278],
        [-1.9419,  0.2047, -1.4766]], requires_grad=True)
tensor([[-11867.5723, -14085.4463,  -8381.6484],
        [-26858.1172, -28219.9961, -17720.8008]])


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-4
        b -= b.grad * 1e-4
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5294, grad_fn=<DivBackward0>)


In [ ]:
import numpy as np
from torch import nn
import torch
# using inbuild functions
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

batch=5
# train_ds = datasets.ImageGolder('/path/',transform=transform)
train_ds = TensorDataset(inputs,targets)
train_dl = DataLoader(train_ds,batch,shuffle=True)


model = nn.Linear(3, 2)
# it automatically initializes weights and biases inbuild

print(model.weight)
print(model.bias)
# or
print(list(model.parameters()))


import torch.nn.functional as F
loss_fn  = F.mse_loss
opt = torch.optim.SGD(model.parameters(), lr=1e-4)

def fit(epochs,loss_fn,optim,train_dl,model):
  
  for epoch in range(epochs):
    for xb,yb in train_dl:
        # 1. Generate predictions
        pred = model(xb)
        
        # 2. Calculate loss
        loss = loss_fn(pred, yb)
        
        # 3. Compute gradients
        loss.backward()
        
        # 4. Update parameters using gradients
        opt.step()
        
        # 5. Reset the gradients to zero
        opt.zero_grad()
    
    # Print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

NameError: ignored